### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by sober11** [krapnikkk/fgui-restore#5]
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 8388604. Received 8388608
    at new NodeError (node:internal/errors:393:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt32BE (node:internal/buffer:309:5)
    at Jimp.<anonymous> (C:\Users\sober\Downloads\fgui-restore\node_modules\@jimp\plugin-crop\dist\index.js:43:37)
    at scan (C:\Users\sober\Downloads\fgui-restore\node_modules\@jimp\utils\dist\index.js:53:9)
    at Jimp.scanQuiet (C:\Users\sober\Downloads\fgui-restore\node_modules\@jimp\core\dist\index.js:1262:32)
    at Jimp.cropQuiet (C:\Users\sober\Downloads\fgui-restore\node_modules\@jimp\plugin-crop\dist\index.js:42:12)
    at Jimp.<computed> [as crop] (C:\Users\sober\Downloads\fgui-restore\node_modules\@jimp\core\dist\index.js:1176:23)
    at C:\Users\sober\Downloads\fgui-restore\lib.js:3626:40 {
  code: 'ERR_OUT_OF_RANGE',
  methodName: 'crop',
  eventName: 'error'
}

请问，如何解决这个问题？

**Comment by sober11** [comment]
![ImageGIF2_atlas0](https://user-images.githubusercontent.com/42740657/208579761-ad55646b-cd24-4c75-9c5f-fa7e714fe1e1.png)

**Comment by sober11** [comment]
[temp.zip](https://github.com/krapnikkk/fgui-restore/files/10267472/temp.zip)

**Comment by krapnikkk** [comment]
图集和描述文件匹配不上导致的
